In [1]:
import pandas as pd

In [3]:
data = pd.read_csv("stats.csv")

In [4]:
data.head()

   problem_id   model prompt_detail  temp   i  levenshtein distance
0           1  gpt3.5             L   0.3   1                    14
1           1  gpt3.5             L   0.3   2                    14
2           1  gpt3.5             L   0.3  11                    14
3           1  gpt3.5             L   0.3  19                    14
4           1  gpt3.5             L   0.3  40                    14

In [5]:
data['problem_id'].unique()

array([ 1,  2,  3,  4,  5,  6,  8, 13, 14, 15, 17, 18, 23, 24,  7,  9, 10,
       11, 12, 16, 19, 20, 21, 22, 25])

In [15]:
print(data.groupby(["model"]).count()['problem_id'].to_latex())

\begin{tabular}{lr}
\toprule
 & problem_id \\
model &  \\
\midrule
gemini & 51 \\
gpt3.5 & 1039 \\
gpt4 & 149 \\
llama & 221 \\
mistral & 32191 \\
\bottomrule
\end{tabular}

In [6]:
data.groupby(["model", "problem_id"]).describe()

                      temp                                                \
                     count      mean       std  min   25%  50%  75%  max
model   problem_id
gemini  23             1.0  1.000000       NaN  1.0  1.00  1.0  1.0  1.0
        24            50.0  0.588000  0.312096  0.1  0.30  0.7  0.7  1.0
gpt3.5  1            547.0  0.564717  0.320396  0.1  0.30  0.5  1.0  1.0
        2            132.0  0.812879  0.207274  0.3  0.70  1.0  1.0  1.0
        3             77.0  0.872727  0.177435  0.5  0.70  1.0  1.0  1.0
        4            127.0  0.843307  0.199440  0.3  0.70  1.0  1.0  1.0
        5             88.0  0.830682  0.218857  0.3  0.70  1.0  1.0  1.0
        6             65.0  0.893846  0.159958  0.5  0.70  1.0  1.0  1.0
        13             1.0  0.700000       NaN  0.7  0.70  0.7  0.7  0.7
        15             1.0  0.700000       NaN  0.7  0.70  0.7  0.7  0.7
        17             1.0  1.000000       NaN  1.0  1.00  1.0  1.0  1.0
gpt4    6              1.0  1.000000       NaN  1.0  1.00  1.0  1.0  1.0
        8              2.0  1.000000  0.000000  1.0  1.00  1.0  1.0  1.0
        14            48.0  0.714583  0.296066  0.1  0.50  0.7  1.0  1.0
        15            15.0  0.846667  0.241622  0.3  0.70  1.0  1.0  1.0
        17             1.0  1.000000       NaN  1.0  1.00  1.0  1.0  1.0
        18             1.0  1.000000       NaN  1.0  1.00  1.0  1.0  1.0
        23             3.0  0.900000  0.173205  0.7  0.85  1.0  1.0  1.0
        24            78.0  0.693590  0.306357  0.1  0.50  0.7  1.0  1.0
llama   13             1.0  0.700000       NaN  0.7  0.70  0.7  0.7  0.7
        23             1.0  0.300000       NaN  0.3  0.30  0.3  0.3  0.3
        25           219.0  0.583562  0.293201  0.1  0.30  0.5  0.7  1.0
mistral 1           1337.0  0.491324  0.308196  0.1  0.30  0.5  0.7  1.0
        2            798.0  0.493358  0.308993  0.1  0.30  0.5  0.7  1.0
        3           1087.0  0.466145  0.307808  0.1  0.10  0.5  0.7  1.0
        4           1034.0  0.467021  0.316144  0.1  0.10  0.5  0.7  1.0
        5           1241.0  0.475020  0.306891  0.1  0.30  0.5  0.7  1.0
        6           1409.0  0.499929  0.307633  0.1  0.30  0.5  0.7  1.0
        7           1240.0  0.475403  0.302905  0.1  0.30  0.5  0.7  1.0
        8           1451.0  0.506547  0.307703  0.1  0.30  0.5  0.7  1.0
        9           1374.0  0.492140  0.305801  0.1  0.30  0.5  0.7  1.0
        10          1259.0  0.472200  0.302542  0.1  0.30  0.5  0.7  1.0
        11          1384.0  0.494653  0.305529  0.1  0.30  0.5  0.7  1.0
        12          1389.0  0.496256  0.307215  0.1  0.30  0.5  0.7  1.0
        13          1456.0  0.508448  0.308757  0.1  0.30  0.5  0.7  1.0
        14          1403.0  0.497078  0.305954  0.1  0.30  0.5  0.7  1.0
        15          1444.0  0.505194  0.307687  0.1  0.30  0.5  0.7  1.0
        16          1156.0  0.479671  0.310498  0.1  0.30  0.5  0.7  1.0
        17          1215.0  0.478354  0.309515  0.1  0.30  0.5  0.7  1.0
        18          1349.0  0.486509  0.303606  0.1  0.30  0.5  0.7  1.0
        19          1220.0  0.471393  0.304211  0.1  0.30  0.5  0.7  1.0
        20          1271.0  0.485208  0.306828  0.1  0.30  0.5  0.7  1.0
        21          1369.0  0.492768  0.306578  0.1  0.30  0.5  0.7  1.0
        22          1330.0  0.485714  0.304677  0.1  0.30  0.5  0.7  1.0
        23          1451.0  0.508684  0.309003  0.1  0.30  0.5  0.7  1.0
        24          1474.0  0.513161  0.310404  0.1  0.30  0.5  0.7  1.0
        25          1050.0  0.474000  0.311276  0.1  0.10  0.5  0.7  1.0

                         i             ...              levenshtein distance  \
                     count       mean  ...    75%   max                count
model   problem_id                     ...
gemini  23             1.0  84.000000  ...  84.00  84.0                  1.0
        24            50.0  51.420000  ...  74.75  99.0                 50.0
gpt3.5  1            547.0  48.371115  ...  73.00  99.0                547.0
        2            132.0  42.901515  ...  65.00  96.0                132.0
        3             77.0  38.727273  ...  57.00  96.0                 77.0
        4            127.0  40.259843  ...  57.00  96.0                127.0
        5             88.0  48.738636  ...  71.25  98.0                 88.0
        6             65.0  54.307692  ...  85.00  99.0                 65.0
        13             1.0  53.000000  ...  53.00  53.0                  1.0
        15             1.0  11.000000  ...  11.00  11.0                  1.0
        17             1.0   7.000000  ...   7.00   7.0                  1.0
gpt4    6              1.0  31.000000  ...  31.00  31.0                  1.0
        8              2.0  32.000000  ...  32.50  33.0                  2.0
        14            48.0  50.583333  ...  75.50  99.0                 48.0
        15            15.0  46.400000  ...  62.50  70.0                 15.0
        17             1.0   7.000000  ...   7.00   7.0                  1.0
        18             1.0  84.000000  ...  84.00  84.0                  1.0
        23             3.0  40.000000  ...  53.00  53.0                  3.0
        24            78.0  54.782051  ...  79.00  99.0                 78.0
llama   13             1.0  50.000000  ...  50.00  50.0                  1.0
        23             1.0  95.000000  ...  95.00  95.0                  1.0
        25           219.0  48.465753  ...  73.00  99.0                219.0
mistral 1           1337.0  49.470456  ...  74.00  99.0               1337.0
        2            798.0  50.096491  ...  75.00  99.0                798.0
        3           1087.0  49.882245  ...  75.00  99.0               1087.0
        4           1034.0  49.129594  ...  74.00  99.0               1034.0
        5           1241.0  49.669621  ...  75.00  99.0               1241.0
        6           1409.0  49.557842  ...  74.00  99.0               1409.0
        7           1240.0  49.704839  ...  74.25  99.0               1240.0
        8           1451.0  49.676775  ...  74.50  99.0               1451.0
        9           1374.0  49.339156  ...  75.00  99.0               1374.0
        10          1259.0  49.215250  ...  75.00  99.0               1259.0
        11          1384.0  49.693642  ...  75.00  99.0               1384.0
        12          1389.0  49.665947  ...  74.00  99.0               1389.0
        13          1456.0  49.517170  ...  74.00  99.0               1456.0
        14          1403.0  49.600143  ...  74.50  99.0               1403.0
        15          1444.0  49.520776  ...  74.25  99.0               1444.0
        16          1156.0  49.544118  ...  75.00  99.0               1156.0
        17          1215.0  49.032099  ...  74.00  99.0               1215.0
        18          1349.0  49.223128  ...  74.00  99.0               1349.0
        19          1220.0  49.343443  ...  75.00  99.0               1220.0
        20          1271.0  49.790716  ...  75.00  99.0               1271.0
        21          1369.0  49.281227  ...  74.00  99.0               1369.0
        22          1330.0  49.368421  ...  74.00  99.0               1330.0
        23          1451.0  49.560992  ...  75.00  99.0               1451.0
        24          1474.0  49.513569  ...  75.00  99.0               1474.0
        25          1050.0  49.427619  ...  74.00  99.0               1050.0

                                                                          \
                          mean         std    min     25%    50%     75%
model   problem_id
gemini  23            3.000000         NaN    3.0    3.00    3.0    3.00
        24            3.000000    0.000000    3.0    3.00    3.0    3.00
gpt3.5  1            76.555759  217.224353    7.0   14.00   14.0   14.00
        2           191.492424  227.756114    7.0   62.00   62.0  308.25
        3           143.402597  174.067989   10.0   61.00   62.0  208.00
        4           128.023622  193.096261    7.0   14.00   62.0  176.00
        5           123.965909  171.212810    7.0   14.00   62.0  151.75
        6           131.369231  157.469796    3.0   14.00   14.0  220.00
        13            3.000000         NaN    3.0    3.00    3.0    3.00
        15            3.000000         NaN    3.0    3.00    3.0    3.00
        17           14.000000         NaN   14.0   14.00   14.0   14.00
gpt4    6           261.000000         NaN  261.0  261.00  261.0  261.00
        8            14.500000    0.707107   14.0   14.25   14.5   14.75
        14          663.520833  241.438507  310.0  489.25  600.0  869.25
        15          703.800000  233.707143  308.0  537.50  688.0  881.50
        17           14.000000         NaN   14.0   14.00   14.0   14.00
        18          642.000000         NaN  642.0  642.00  642.0  642.00
        23          324.000000  158.009493  167.0  244.50  322.0  402.50
        24          578.935897  203.278348   14.0  448.00  551.5  693.50
llama   13           10.000000         NaN   10.0   10.00   10.0   10.00
        23           10.000000         NaN   10.0   10.00   10.0   10.00
        25            4.000000    0.000000    4.0    4.00    4.0    4.00
mistral 1            13.922214    0.848524    7.0   14.00   14.0   14.00
        2            13.819549    1.646263    7.0   14.00   14.0   14.00
        3            14.472861   10.952137    7.0   14.00   14.0   14.00
        4            14.442940   12.564688    7.0   14.00   14.0   14.00
        5            14.124093    6.583514    3.0   14.00   14.0   14.00
        6            14.134847    9.020745    7.0   14.00   14.0   14.00
        7            13.978226    2.710160    7.0   14.00   14.0   14.00
        8            14.894555   20.698140    7.0   14.00   14.0   14.00
        9            14.235080    8.993121    3.0   14.00   14.0   14.00
        10           14.018268    5.960694    7.0   14.00   14.0   14.00
        11           15.021676   23.512852    7.0   14.00   14.0   14.00
        12           14.674586   15.171330    7.0   14.00   14.0   14.00
        13           15.098901   18.714086    7.0   14.00   14.0   14.00
        14           14.629366   14.883122    7.0   14.00   14.0   14.00
        15           15.517313   24.996030    7.0   14.00   14.0   14.00
        16           14.434256   10.522291    7.0   14.00   14.0   14.00
        17           13.805761    1.173625    7.0   14.00   14.0   14.00
        18           15.152706   20.224199    7.0   14.00   14.0   14.00
        19           14.081967    7.629108    3.0   14.00   14.0   14.00
        20           14.048780    5.845584    7.0   14.00   14.0   14.00
        21           14.609204   14.188114    7.0   14.00   14.0   14.00
        22           14.619549   30.242256    7.0   14.00   14.0   14.00
        23           14.682288   13.073177    7.0   14.00   14.0   14.00
        24           14.272049    8.952462    7.0   14.00   14.0   14.00
        25            8.160000    3.216544    7.0    8.00    8.0    8.00


                       max
model   problem_id
gemini  23             3.0
        24             3.0
gpt3.5  1           1343.0
        2            852.0
        3            836.0
        4           1664.0
        5            947.0
        6            548.0
        13             3.0
        15             3.0
        17            14.0
gpt4    6            261.0
        8             15.0
        14          1346.0
        15          1116.0
        17            14.0
        18           642.0
        23           483.0
        24          1098.0
llama   13            10.0
        23            10.0
        25             4.0
mistral 1             25.0
        2             45.0
        3            272.0
        4            304.0
        5            235.0
        6            351.0
        7            105.0
        8            665.0
        9            335.0
        10           222.0
        11           816.0
        12           347.0
        13           464.0
        14           463.0
        15           489.0
        16           242.0
        17            20.0
        18           418.0
        19           278.0
        20           203.0
        21           332.0
        22          1075.0
        23           379.0
        24           338.0
        25            76.0

[47 rows x 24 columns]